### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alex-taxiera** [alex-taxiera/TuxedoMan#5]
~~FUCKING GET THE MODULES OFF OF GITHUB
Require nodejs to be installed obviously, then auto download the dependencies.~~

Test

- [x] 1. Server addition/deletion
- [x] 2. Auto reconnect
- [x] 3. EAI_AGAIN resetting s object
- [x] 4. Bot leaves, then errors on join event because encoder does not exist, check if encoder exists first
- [x] 4.1. do if value/!value instead of checking =/!== undefined

Bugs

- [x] 1. On reconnect after disconnect, bot connects to server twice then becomes unresponsive (suspect testing redundant connect)
- [x] 2. Changing volume while no encoder breaks bot
- [x] 3. Unhandled promise with preferences embed,

New Features

- [x] 1. Create command to toggle now playing announcments (global and for just autoplay songs)
- [x] 2. Create command to toggle autoplay
- [x] 3. Create command to toggle memes
- [x] 4. Create command to show current preferences
- [x] 5. Delete nsfw dva after some time
- [x] 6. Game role switcher
- [x] 7. Create function to check if user has permission for a function, add perm level to commands
- [x] 8. File set up.
- [x] 9. Readme: nodejs, npm install, token.txt, ytkey.txt, playlist info
- [x] 10. Only users in relevant voice channel can use voice commands

~~11. Vote to skip, reliant on number of people in voice channel, configurable percentage of people for vote to pass~~ moved to #17 
~~12. Add and create playlist files through bot, option to add additional songs or playlists to a playlist file, option to play saved playlist file, select which playlist(s) are eligible for auto queue, separate playlist folders for each server, can put the mp3 file in there too~~ moved to #18 
~~13. Soundcloud searching, playlists, and downloading~~ moved to #16 
- [x] 14. Adding and deleting game roles actually creates or deletes the role for the guild

Fixes

- [x] 1. Account for missing channels upon restart + channel deletion during runtime
- [x] 2. Account for server "deletion" during runtime
- [x] 3. Account for server "addition" during runtime
- [x] 4. Account for channel permisions at start up: a. Voice channel speak b. Text channel send
- [x] 5. Account for channel permisions during run time: a. Voice channel speak b. Text channel send
- [x] 6. Change role checking for loop to .hasRole(role) promise
- [x] 7. DM owner when no text channels with send perm, or voice channels with connect + speak perm
- [x] 8. Manage Message perm check is fucked
- [x] 9. Volume loud as fuck, take input between 0-200 and divide by 2
- [x] 10. Different message for setting volume to same value.
- [x] 11. Prefs should display volume as the user input 0-200 to clear confusion about volume level
- [x] 12. Remove roles from file for game roles if they get deleted by a user

~~13. Maybe don't rewrite the entire file every time? idk if that is really an option unless i can use a database thing~~
~~14. No more global bot, only global to events file, then events pass him around to everything~~ moved to #19
~~15. Either write a DB module or integrate one for my global.g variable~~ moved to #20

New Songs
- [ ] 1. Silvagunner
